### ISSUE TITLE
Unable to download ndjson result file

### ISSUE THREAD

**Issue by greenwoodma** [GateNLP/4cat#4]
Once a dataset has been collected, it seems impossible (at least in recent versions of chrome based browsers) to download the ndjson version of the dataset. I can download the CSV version without issue, but clicking on the ndjson link has no effect. Checking the developer console and I find this error

```fourcat-dev.internal.gate.ac.uk/:1 Mixed Content: The site at 'https://fourcat-dev.internal.gate.ac.uk/' was loaded over a secure connection, but the file at 'https://fourcat-dev.internal.gate.ac.uk/result/natgeosociety-efe6596c577840069bca960fc0da5605.ndjson/' was redirected through an insecure connection. This file should be served over HTTPS. This download has been blocked. See https://blog.chromium.org/2020/02/protecting-users-from-insecure.html for more details.```

which is odd given that all the URLs mentioned appear to be https so not sure what is going on internally. Looking further it seems that the initial URL ``https://fourcat-dev.internal.gate.ac.uk/result/natgeosociety-efe6596c577840069bca960fc0da5605.ndjson`` redirects via a 308 response to ``http://fourcat-dev.internal.gate.ac.uk/result/natgeosociety-efe6596c577840069bca960fc0da5605.ndjson/`` which is plain http not https. This then redirects to ``https://fourcat-dev.internal.gate.ac.uk/result/natgeosociety-efe6596c577840069bca960fc0da5605.ndjson/`` which as far as I can see is the same URL just now the https version. Unfortunately as that redirect chain goes to via an unsecure http URL the browsers won't allow the final URL to be accessed even though the server responds with a 200 and the file contents.

**Comment by muneerahp** [comment]
Fixed with extra url on controller as suggested on calling (so should be able to at least download the files now!), along with one extra change.
